
export default {
  SET_TOKEN: 'SET_TOKEN', // 保存token
  REMOVE_TOKEN: 'REMOVE_TOKEN', // 删除token
  SET_USER: 'SET_USER', // 保存用户信息
  REMOVE_USER: 'REMOVE_USER',  // 删除用户信息
  LOGIN_OUT: 'LOGIN_OUT', // 退出登录
  SET_REMEMBER_ACCOUNT: 'SET_REMEMBER_ACCOUNT', // 记账账号
  PUT_CACHE_PAGE: 'PUT_CACHE_PAGE',
  REMOVE_CACHE_PAGE: 'REMOVE_CACHE_PAGE',
  SHOW_PAGE_LOADING: 'SHOW_PAGE_LOADING'
}